# Guild-specific Config file

guild:
    id: 717010362234568764
    invite: https://discord.gg/A2bGdepRZQ
    name: KEN's Braincells

bot:
    prefix:

ext:
    adv_replies:
        enabled: true
    danked_memer:
        enabled: true
    messagehook:
        enabled: true
    reactomatic:
        enabled: true
    welcomer:
        enabled: true
        welcome_channel: 747499579527659540
    anti_spam:
        enabled: true
    counting:
        enabled: true
    mod_utils:
        enabled: true
    nerd_utils:
        enabled: true
    simple_games:
        enabled: true
