# Guild-specific Config file

guild:
    id: 839457899360157706
    invite:
    name: yes

bot:
    prefix:

ext:
    adv_replies:
    danked_memer:
    messagehook:
    reactomatic:
    welcomer:
        welcome_channel: 839457899360157709
